#!/bin/python3

import sys


n = int(input().strip())
a = []
for a_i in range(n):
    a_t = [int(a_temp) for a_temp in input().strip().split(' ')]
    a.append(a_t)
sum=sum1=0
for i in range(n):
    for j in range(n):
        if(i==j):
            sum+=a[i][j]
        if(i+j==n-1):
            sum1+=a[i][j]
print(abs(sum-sum1))
