#!/bin/python3

import sys


n = int(input().strip())
ar = list(map(int, input().strip().split(' ')))
a1 = len(list(filter(lambda x:x>0,ar)))
a2 = len(list(filter(lambda x:x<0,ar)))
a3 = len(list(filter(lambda x:x==0,ar)))
print("%.6f" % (a1/n))
print("%.6f" % (a2/n))
print("%.6f" % (a3/n))
