#!/bin/python3

import sys


n = int(input().strip())
ar = list(map(int, input().strip().split(' ')))
a1=a2=a3=0
for i in ar:
    if(i>0):
        a1+=1
    elif(i<0):
        a2+=1
    else:
        a3+=1

print("%.6f" % round((a1/n),6))
print("%.6f" % round((a2/n),6))
print("%.6f" % round((a3/n),6))
