#!/bin/python3

import sys

n=int(input())
a=list(map(int,input().split()))
key=a[len(a)-1]
if(n>1):
    for i in range(n-1,-1,-1):
        if(key<a[i-1] and i!=0):
            a[i]=a[i-1]
            for j in a:
                print(j,end=" ")
            print()
        else:
            a[i]=key
            break

for k in a:
    print(k,end=" ")
