#!/bin/python3

import sys

n=input()
a=list(map(int,input().split()))
cnt=0
for j in range(1,len(a)):
    key=a[j]
    i=j-1

    while(i>=0 and a[i]>key):
        a[i+1]=a[i]
        cnt+=1
        i=i-1
    a[i+1]=key
print(cnt)
