#!/bin/python3

import sys

for i in range(int(input())):
    n,k=map(int,input().split())
    no=list(map(int,input().split()))
    no=list(filter(lambda x:x<=0,no))
    print("YES" if len(no)<k else "NO")
