#!/bin/python3

import sys

s,t = input().strip().split(' ')
s,t = [int(s),int(t)]
a,b = input().strip().split(' ')
a,b = [int(a),int(b)]
m,n = input().strip().split(' ')
m,n = [int(m),int(n)]
apple = [int(apple_temp) for apple_temp in input().strip().split(' ')]
orange = [int(orange_temp) for orange_temp in input().strip().split(' ')]
cnt1=cnt2=0
for i in apple:
    if(a+i in range(s,t+1)):
        cnt1+=1
for j in orange:
    if(b+j in range(s,t+1)):
        cnt2+=1
print(cnt1)
print(cnt2)       
