#!/bin/python3

import sys

s,t=list(map(int,input().split()))
a=list(map(int,input().split()))
b=list(map(int,input().split()))
maxa=max(a)
minb=min(b)
cnt1=0
while(maxa<=min(b)):
    cnt=0
    for i in a:
        if(maxa%i!=0):
            cnt=1
            break

    for i in b:
        if(i%maxa!=0):
            cnt=1
            break
    maxa+=1
    if(cnt!=1):
        cnt1+=1
print(cnt1)
