#!/bin/python3

import sys

n=int(input())
a=list(map(int,input().split()))
max1=min1=a[0]
cnt1=cnt2=0

for i in a[1:]:
    if(i>max1):
        max1=i
        cnt1+=1
    if(i<min1):
         min1=i
         cnt2+=1

print(cnt1,cnt2)
