#!/bin/python3

import sys

s,n,m=map(int,input().split())
a=list(map(int,input().split()))
b=list(map(int,input().split()))
max1=-1
for i in a:
    for j in b:
        if(i+j>max1 and i+j<=s):
            max1=i+j
print(max1)
