#!/bin/python3

import os
import sys

from collections import Counter
for j in range(int(input())):
    n=int(input())
    s=input()
    ss=dict(Counter(s))
    if(ss.get('_')!=None):
        for i in ss:
            if(ss[i]==1 and i!="_"):
                print("NO")
                break

        else:print("YES")
    else:
            x=s[0]
            cnt = 0
            for i in s:
                if (x != i):
                    x = i
                    if (cnt == 1):
                        print("NO")
                        break
                    cnt = 1
                else:
                    cnt += 1
            else:
                if (cnt == 1):
                    print("NO")
                else:
                    print("YES")
