#!/bin/python3

import sys

n=int(input())
a=list(map(int,input().split()))
cnt=i=0
while(i<n-1):
    if(i<=n-3 and a[i+2]==0):
        i+=2
        cnt+=1
    else:
        i+=1
        cnt+=1
print(cnt)
