#!/bin/python3

import sys

from collections import Counter
s=input()
a=list(map(int,input().split()))
l={k for k,v in filter(lambda x:x[1]>=2,Counter(a).items())}
a1=[]

for i in l:
    cnt = n = 0
    for j in range(len(a)-1,-1,-1):
        if(i==a[j]):
            n=j-n
            cnt+=1
            if(cnt==2):
                a1.append(abs(n))
                break
print(min(a1) if(len(a1)>0) else -1)
