#!/bin/python3

h=int(input())
m=int(input())
d={1:"one",2:"two",3:"three",4:"four",5:"five",6:"six",7:"seven",
        8:"eight",
        9:"nine",
        10:"ten",
        11:"eleven",
        12:"twelve",
       13:"thirteen",
        14:"fourteen",
        15:"quarter",
        16:"sixteen",
       17:"seventeen",
        18:"eighteen",
        19:"nineteen",
        20:"twenty",
        21:"twenty one",
        22:"twenty two",
        23:"twenty three",
        24:"twenty four",
        25:"twenty five",
        26:"twenty six",
        27:"twenty seven",
        28:"twenty eight",
        29:"twenty nine"

   }
if(m==0):
    print("{} o' clock".format(d[h]))
elif(m>=30):
    if(h!=12):
        if(m==30):
            print("half past {}".format(d[h]))
        elif(m-30==15):
            print("{0} to {1}".format(d[m-30],d[h+1]))
        else:
            if(m-30!=1):
                print("{} minutes to {}".format(d[60-m],d[h+1]))
            else:
                print("{} minutes to {}".format(d[60 - m], d[h + 1]))
    else:
        if(m - 30 == 15):
             print("{0} to {1}".format(d[m - 30], d[1]))
        else:
             print("{} minutes to {}".format(d[60 - m], d[1]))
else:
    if(m==15):
        print("{} past {}".format(d[m],d[h]))
    else:
        if(m!=1):
            print("{} minutes past {}".format(d[m],d[h]))
        else:
            print("{} minute past {}".format(d[m], d[h]))
