#!/bin/python3

import sys

s=input()
cnt=0
for i in range(0,len(s)-2,3):
    if(s[i]!='S'):
        cnt+=1
    if(s[i+1]!='O'):
        cnt+=1
    if (s[i + 2] != 'S'):
        cnt += 1

print(cnt)

