#!/bin/python3
from collections import OrderedDict
a=OrderedDict()
for i in range(int(input())):
    n=input()
    if(a.get(n)!=None):
        a[n]+=1
    else:
        a[n]=1

print(len(a))
for j in a:
    print(a.get(j),end=" ")
