#!/bin/python3
import sys

n=int(input())
a="hackerrank"
for j in range(n):
    s=input()
    cnt=0
    for i in s:
        if(a[cnt]==i):
            cnt+=1
        if(cnt==len(a)):
            break
    print("YES" if cnt==len(a) else "NO")
