#!/bin/python3

n = int(input())
a = list(input())
l = u = d = s = 0
special_characters = "!@#$%^&*()-+"
for i in a:
    if (i.isalnum()):
        if(i.isupper() and u==0):
            u=1
        elif(i.islower() and l==0):
            l=1
        elif(i.isdigit() and d==0):
            d=1
    elif(i in special_characters and s==0):
        s=1
    if(u+l+d+s==4):
        break
if(n<6):
    print(max(4-(u+l+d+s),6-n))
else:
    print(4-(u+l+d+s))
