#!/bin/python3

import sys

s=list(input())
i=1
ss=""
while(i<len(s)):
    if(s[i-1]==s[i]):
        del s[i-1]
        del s[i-1]

        i=1
    else:
          i+=1
for j in range(len(s)):
    ss+=s[j]
if(ss!=""):
    print(ss)
else:print("Empty String")
