#!/bin/python3

import sys

for j in range(int(input())):
    s=input()
    l=len(s)
    cnt=0
    for i in range(l//2):
        if(s[i]!=s[l-i-1]):
            cnt+=abs(ord(s[i])-ord(s[l-i-1]))
    print(cnt)
